//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by uEnergyOTAUpdateTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ANOTHER_PROCESS_USING_RADIO 77
#define IDS_DEV_CONNECTING              78
#define IDS_DEV_CONTIMEOUT              79
#define IDS_BA                          80
#define IDS_BATTERY_FAIL                80
#define IDS_OTA_FILE_MISSING            81
#define IDS_STRING82                    82
#define IDS_GATT_SERV_CHGD_IND          82
#define IDS_PASSKEY_HEADING             83
#define IDS_PASSKEY_DISPLAY_MESSAGE     84
#define IDS_STRING85                    85
#define IDS_PAIRING_FAILURE_REPEATED_ATTEMPTS 85
#define IDS_FAILURE_IMAGE_CORRUPT       85
#define IDS_IMAGE_TRANSFER_FAILED       85
#define IDS_FAILURE_IMAGE_BIG           86
#define IDS_IMAGE_TRANSFER_ABORTED      86
#define IDS_OTA_TRANSFER_FAILED         87
#define IDS_FAILURE_UNKNOWN_REASON      87
#define IDS_OTA_DNLOAD_CANCELLED        88
#define IDS_OTA_IMAGE_BIG_ERR           89
#define IDS_OTA_BATTERY_LOW_ERR         90
#define IDS_OTA_IMAGE_CORRUPT_ERR       91
#define IDS_OTA_CHECK_BATT_LEVEL        93
#define IDS_BATT_CFG_NOTIFICATION       95
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_UENERGYOTAUPDATETOOL_DIALOG 102
#define IDS_APP_INIT_ERROR              102
#define IDS_APP_START_ERROR             103
#define IDS_APP_INIT                    104
#define IDS_OTA_SETMODE_ERROR           105
#define IDS_OTA_SETCURAPP_ERROR         106
#define IDS_OTA_CURAPP                  107
#define IDS_OTA_APP_SUPPORTED           108
#define IDS_OTA_BOOTLDR_SUPPORTED       109
#define IDS_OTA_NOT_SUPPORTED           110
#define IDS_OTA_CR_CFM_ERROR            111
#define IDS_OTA_BLDR_VERSION            112
#define IDS_OTA_SELECT_IMAGEFILE        113
#define IDS_APP_HW_NOTREADY             114
#define IDS_APP_HW_READY                115
#define IDS_OTA_ENCR_ERROR              116
#define IDS_OTA_AES_DLLNOTFOUND         117
#define IDS_OTA_AES_DLLFOUND            118
#define IDS_OTA_READ_BDADDRERROR        119
#define IDS_OTA_READ_CURAPPERROR        120
#define IDS_OTA_RESET_DEVICE            121
#define IDS_OTA_DNLOAD_START            122
#define IDS_OTA_IMAGE_MERGE_FAILED      123
#define IDS_APP_SCANNING                124
#define IDS_APP_STOPSCAN                125
#define IDS_OTA_DNLOAD_SUCCESS          126
#define IDS_OTA_DNLOAD_FAILED           127
#define IDS_APP_DISCONNECTED            128
#define IDS_APP_DB_READ                 129
#define IDR_LOG_MENU                    130
#define IDS_APP_PAIRING_RCVD            130
#define IDS_APP_PAIRING_FAILURE         131
#define IDS_APP_BONDED                  132
#define IDS_APP_BL_CONNECTED            133
#define IDR_MAINFRAME                   133
#define IDS_OTA_GET_CLVAL               134
#define IDD_PROMPT_USER                 134
#define IDS_OTA_GET_BLVER               135
#define IDS_APP_CONNECTED               136
#define IDS_STRING137                   137
#define IDS_OTA_MERGE_KEYS              137
#define IDS_OTA_CFG_NOT_ERR             138
#define IDS_OTA_READ_BLVER_ERR          139
#define IDS_OTA_GET_CURAPP              140
#define IDS_OTA_SET_CURAPP              141
#define IDS_OTA_GET_BDADDR              142
#define IDS_OTA_GET_XTALTRIM            143
#define IDS_OTA_GET_IDROOT              144
#define IDS_OTA_SWITCH_BL               145
#define IDS_OTA_SETCUTAPP_SUCCESS       146
#define IDS_OTA_READ_XTALTRIM           147
#define IDS_OTA_CURAPP_ERROR            148
#define IDS_OTA_READ_BDADDRESS          149
#define IDS_OTA_CFG_NOTIFICATION        150
#define IDS_OTA_CFG_INDICATION          151
#define IDS_OTA_GET_ENCRROOT            152
#define IDS_OTA_READ_IDTYROOT           153
#define IDS_OTA_READ_ENCRROOT           154
#define IDS_OTA_READ_XTALTRIM_ERROR     155
#define IDS_OTA_READ_IDROOT_ERROR       156
#define IDS_STRING157                   157
#define IDS_OTA_READ_ENROOT_ERROR       157
#define IDS_OTA_READ_CSBLOCK            158
#define IDS_OTA_READ_CSBLOCKFAILED      159
#define IDS_DONGLE_REMOVAL              160
#define IDS_RADIO_ABSENT                161
#define IDS_DRIVER_ABSENT               162
#define IDS_PROCESS_RUNNING             163
#define IDS_APP_TITLE                   164
#define IDS_STRING165                   165
#define IDS_OTA_DOWNLOADMSG             165
#define IDS_AUTH_VAL                    166
#define IDS_OTA_CR_CFM_ERROR2           167
#define IDS_OTA_CR_CFM_SUCCESS          167
#define IDC_SELECTFILE_BUTTON           1000
#define IDC_IMAGE_PATH                  1001
#define IDC_EDIT2                       1002
#define IDC_SECRETKEY_EDIT              1002
#define IDC_SCAN_BUTTON                 1003
#define IDC_SCAN_BUTTON2                1004
#define IDC_REMOVE_BUTTON               1004
#define IDC_DEVICE_LIST                 1005
#define IDC_UPDATE_BUTTON               1006
#define IDC_PROGRESS                    1007
#define IDC_LOGGING_LIST                1009
#define IDC_ABOUT_BOX                   1010
#define IDC_SYSLINK1                    1012
#define IDC_GENERATEKEY_BTN             1013
#define IDC_CHECK_AUTH                  1014
#define IDC_ENABLE_MITM                 1015
#define IDC_USER_ENTRY                  1016
#define IDC_USER_PROMPT_TEXT            1017
#define ID_LOG_SAVELOG                  32772
#define ID_LOG_CLEARLOG                 32773
#define ID_LOG_AUTOLOG                  32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
