/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from depend_Release_CSR101x_A05/app_gatt_db.db_
 */

#include "depend_Release_CSR101x_A05/app_gatt_db.h"

/* GATT database */
uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Characteristic Declaration 2a05 */
    0x3005, 0x2203, 0x0005, 0x2a00,
    /* 0003:  */
    0xd400,
    /* 0004: Client Characteristic Configuration */
    0x6400,
    /* 0005: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0006: Characteristic Declaration 2a00 */
    0x3005, 0x0a07, 0x0000, 0x2a00,
    /* 0007: . */
    0xd501, 0x0000,
    /* 0008: Characteristic Declaration 2a01 */
    0x3005, 0x0209, 0x0001, 0x2a00,
    /* 0009: . */
    0xd401, 0x0000,
    /* 000a: Characteristic Declaration 2a04 */
    0x3005, 0x020b, 0x0004, 0x2a00,
    /* 000b: H`..X. */
    0xd406, 0x4860, 0x0000, 0x5802,
    /* 000c: Primary Service fef1 */
    0x0002, 0xf1fe,
    /* 000d: Characteristic Declaration c4edc000-9daf-11e3-8000-00025b000b00 */
    0x3013, 0x080e, 0x0000, 0x0b00, 0x5b02, 0x0000, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 000e: . */
    0xc501, 0x0000,
    /* 000f: Characteristic Declaration c4edc000-9daf-11e3-8001-00025b000b00 */
    0x3013, 0x0210, 0x0000, 0x0b00, 0x5b02, 0x0001, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0010: ................ */
    0xc010, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 0011: Characteristic Declaration c4edc000-9daf-11e3-8002-00025b000b00 */
    0x3013, 0x0a12, 0x0000, 0x0b00, 0x5b02, 0x0002, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0012: . */
    0xc401, 0x0000,
    /* 0013: Characteristic Declaration c4edc000-9daf-11e3-8003-00025b000b00 */
    0x3013, 0x1c14, 0x0000, 0x0b00, 0x5b02, 0x0003, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0014: . */
    0xc401, 0x0000,
    /* 0015: Client Characteristic Configuration */
    0x6400,
    /* 0016: Characteristic Declaration c4edc000-9daf-11e3-8004-00025b000b00 */
    0x3013, 0x1c17, 0x0000, 0x0b00, 0x5b02, 0x0004, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0017: . */
    0xc401, 0x0000,
    /* 0018: Client Characteristic Configuration */
    0x6400,
    /* 0019: Characteristic Declaration c4edc000-9daf-11e3-8005-00025b000b00 */
    0x3013, 0x0a1a, 0x0000, 0x0b00, 0x5b02, 0x0005, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 001a: . */
    0xc401, 0x0000,
    /* 001b: Characteristic Declaration c4edc000-9daf-11e3-8006-00025b000b00 */
    0x3013, 0x0a1c, 0x0000, 0x0b00, 0x5b02, 0x0006, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 001c: . */
    0xc401, 0x0000,
};

uint16 *GattGetDatabase(uint16 *len)
{
    *len = sizeof(gattDatabase);
    return gattDatabase;
}

/* End-of-File */
